### ISSUE TITLE
Windows 10 and resolving paths

### ISSUE THREAD

**Issue by lkuklis** [ObjectivityBSS/PSCI#51]
Hi,
I was trying to run simple build task on Windows 10. Unfortunately there is error with executing command. Are you aware of this issue. I suppose this is error related to Windows 10 this same code executed on Win8 runs without any errors.

  `[I] 2016-02-02 18:17:37 [ServerName/username]: (Build-MsBuild.ps1/Build-MsBuild/120) Building package 'ProjectName'.
[I] 2016-02-02 18:17:37 [ServerName/username]: (Invoke-ExternalCommand.ps1/Invoke-ExternalCommand/134) Running external command: "C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe" "C:\Users\username\Projects\ProjectName\ProjectName.sln" /p:Configuration="Release" /p:DeployOnBuild="True" /p:DeployTarget="Package" /p:AutoParameterizationWebConfigConnectionStrings="false" /p:PackageLocation="C:\Users\username\Projects\ProjectName\bin\ProjectName\ProjectName.zip" /nologo /maxcpucount /nodeReuse:false
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[E] 2016-02-02 18:17:37 [ServerName/username]: (Invoke-ExternalCommand.ps1//239) External command failed with exit code '1'.`

**Comment by mgr32** [comment]
Fixed in build #549.
